# Generated by Django 3.0.3 on 2021-04-17 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemData',
            fields=[
                ('UID', models.IntegerField(default=0)),
                ('ItemID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(default='', max_length=150)),
                ('Location', models.CharField(default='', max_length=100)),
                ('Image', models.ImageField(blank=True, default='download.jpeg', upload_to='images')),
                ('Find_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField(default=0)),
                ('branch', models.CharField(default='Computer', max_length=20)),
                ('year', models.CharField(default='', max_length=20)),
                ('contactno', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimData',
            fields=[
                ('ClaimID', models.AutoField(primary_key=True, serialize=False)),
                ('Location', models.CharField(default='', max_length=100)),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ItemData')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
