# Generated by Django 3.0.3 on 2021-04-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdata',
            name='Image',
        ),
        migrations.AddField(
            model_name='itemdata',
            name='item_image',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
