# Generated by Django 3.0.3 on 2021-04-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210418_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdata',
            name='item_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
