# Generated by Django 3.0.3 on 2021-04-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210418_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdata',
            name='item_image',
            field=models.URLField(),
        ),
    ]
