# Generated by Django 3.0.3 on 2021-04-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_lostitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LostItems',
            new_name='LostItem',
        ),
    ]
