# Generated by Django 3.0.3 on 2021-04-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210418_1206'),
    ]


