# Generated by Django 3.0.3 on 2021-04-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210418_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='lostitemID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
