# Generated by Django 3.0.3 on 2021-04-18 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210418_1310'),
    ]

