# Generated by Django 3.0.3 on 2021-04-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210418_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lostitem',
            options={},
        ),

    ]
