# Generated by Django 3.2 on 2021-04-19 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0019_alter_userprofile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='lost_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='FoundData',
            fields=[
                ('lostitemID', models.AutoField(primary_key=True, serialize=False)),
                ('lost_image', models.URLField(null=True)),
                ('title', models.CharField(max_length=2000)),
                ('author', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=2000)),
                ('found_date', models.DateTimeField(auto_now=True)),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
