# Generated by Django 3.2 on 2021-04-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210419_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FoundData',
        ),
    ]
