# Generated by Django 3.2 on 2021-04-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210419_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
