# Generated by Django 3.2 on 2021-04-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_lostitem_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
