# Generated by Django 3.2 on 2021-04-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_lostitem_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdata',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ClaimData',
        ),
    ]
