# Generated by Django 3.2 on 2021-04-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210419_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Image',
            field=models.URLField(default='https://d1nhio0ox7pgb.cloudfront.net/_img/o_collection_png/green_dark_grey/512x512/plain/user.png'),
        ),
    ]
