# Generated by Django 3.2 on 2021-04-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_mage',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='UID',
            field=models.CharField(default='', max_length=20),
        ),
    ]
