# Generated by Django 3.2 on 2021-04-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_rename_user_mage_userprofile_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contactno',
            field=models.CharField(default='', max_length=20),
        ),
    ]
