# Generated by Django 3.2 on 2021-04-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_userprofile_contactno'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdata',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='itemdata',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='itemdata',
            name='company',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
