# Generated by Django 3.2 on 2021-04-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20210421_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdata',
            name='company',
            field=models.CharField(default='Not available', max_length=30),
        ),
    ]
