# Generated by Django 3.2 on 2021-04-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_itemdata_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdata',
            name='author',
            field=models.CharField(default='', max_length=15),
        ),
    ]
