# Generated by Django 3.2 on 2021-04-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_itemdata_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdata',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='itemdata',
            name='author',
        ),
        migrations.RemoveField(
            model_name='itemdata',
            name='color',
        ),
        migrations.RemoveField(
            model_name='itemdata',
            name='company',
        ),
    ]
