# Generated by Django 3.2 on 2021-04-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_itemdata_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdata',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='itemdata',
            name='author',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='itemdata',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='itemdata',
            name='company',
            field=models.CharField(default='Not available', max_length=30),
        ),
    ]
