# Generated by Django 3.2 on 2021-04-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20210421_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdata',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
