# Generated by Django 3.0.3 on 2021-04-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20210421_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostitem',
            old_name='lostitemID',
            new_name='id',
        ),
    ]
